### ISSUE TITLE
How to set values?

### ISSUE THREAD

**Issue by Airyzz** [kevbite/WLED.NET#1]
Hi, I'm trying to use this wrapper to set values, but I cant seem to find any method to do so. Is there a way to do this?

**Comment by kevbite** [comment]
Hey @Airyzz It's not been implemented yet, I only required getting the value for a side project but I'm happy for you to submit a PR if you'd like to add it?

**Comment by kevbite** [comment]
Hey, @Airyzz I've recently merged in a PR that allowed this but also done some alterations today to allow you to call a Post method with a state object. Checkout the updated readme
https://github.com/kevbite/WLED.NET#post-data-to-the-wled-device

**Comment by kevbite** [comment]
I'm going to close this for the time being but if you've got any problems please feel free to open another ticket
