### ISSUE TITLE
Issue with JSON value conversion

### ISSUE THREAD

**Issue by an-da-liu** [kevbite/WLED.NET#4]
When running the sample Program.cs I'm getting:
Unhandled exception. System.Text.Json.JsonException: The JSON value could not be converted to System.Boolean. Path: $.info.leds.wv | LineNumber: 0 | BytePositionInLine: 521.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'Number' as a boolean.

I believe this is due to a change in the MS System.Text.Json handling but I'm unsure how to get around this.

Appologies if this is not an issue but just me not knowing what I'm doing.

**Comment by kevbite** [comment]
Hey @an-da-liu,

Not sure what's going off here as the value `leds.wv` should be a boolean value, but from the description, your device is returning a number within the JSON. (See JSON Spec - https://kno.wled.ge/interfaces/json-api/)

Is there any chance you can do a raw CURL request to the device to look at what values are getting returned and send the JSON response?

Thanks

**Comment by an-da-liu** [comment]
Here is the JSON that came from WLED. Looks like it is sending a 0 instead of False. I'm running Version 0.13.1 on my module, I'll upgrade to 0.13.3 and see if its just a bug in that particular version of WLED. 
[WLED.txt](https://github.com/kevbite/WLED.NET/files/9698032/WLED.txt)

**Comment by an-da-liu** [comment]
[0.13.3.txt](https://github.com/kevbite/WLED.NET/files/9698446/0.13.3.txt)
Appears to have the same value after upgrading to 0.13.3

**Comment by kevbite** [comment]
@an-da-liu ah I think I see what they've done, they've deprecated it and now says to use `leds.lc` instead and that's a byte instead so I guess they've just put the same value in `leds.wv`.

I think the best solution for this is to just remove the property.

I'll update the code and release a new version with the change.

**Comment by kevbite** [comment]
@an-da-liu can you please try using the latest NuGet Package https://www.nuget.org/packages/WLED/2.0.46 and see if that now fixes the problem? If not feel free to re-open the issue.
