### ISSUE TITLE
Issue in Post (segment Request)

### ISSUE THREAD

**Issue by 123tio** [kevbite/WLED.NET#6]
Hello,
a great project. Thanks for your effort. 
But I have a problem to submit a post.
Here is my code so far:

        Dim sr As New SegmentRequest
        sr.Start = 1
        sr.Stop = 65

        Await client.Post(sr)

(i'm trying in vb.net)
Where do I make the mistake?
Would be great if you could help me.
Greetings Tio

Btw. the Exapmples folder just has one file in it.

**Comment by kevbite** [comment]
Hello @123tio 

What's the problem that happens when calling post?

The example is just a simple Get and then post with something changed :-)

**Comment by 123tio** [comment]
Hey @kevbite ,
thank you for your feedback. 
When I try to send a post (as SegmentRequest) I get an error. 
Wrong argument. 
Can you confirm that the call should work as shown above?

**Comment by kevbite** [comment]
Hello, 

Seems you're using the wrong object, if you create a StateRequest and then set the segment values

```vb
    Dim state As New StateRequest
    state.Segments=  // set values here

    Await client.Post(state )
```

**Comment by 123tio** [comment]
i thank you in advance for your effort. 
I feel like this is really a beginner question but maybe you can help anyway. 
I have only one defined segment. and would like to turn on different leds within this segment. 
when i try to execute the function i get the following error. What am I doing wrong?

![image](https://user-images.githubusercontent.com/33313288/206699493-2af1c165-6a6a-4853-8b37-f63597b8dc8f.png)

**Comment by kevbite** [comment]
You'll need to initialise the `state.Segments` array
